[package]
name = "canister_audit_nested_relation_shallow"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = []
candid-export = []

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
icydb = { path = "../../../crates/icydb", default-features = false }
icydb-testing-audit-nested-relation-fixtures = { workspace = true }

[build-dependencies]
icydb = { path = "../../../crates/icydb", default-features = false }
icydb-testing-audit-nested-relation-fixtures = { workspace = true }

[lints]
workspace = true
