[package]
name = "canister_test_sql_bounded"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib"]
path = "../sql/src/lib.rs"

[features]
default = []
candid-export = []
sql = ["icydb/sql"]
local-sql-query = ["sql"]
schema-migration-api = ["icydb/migration"]
schema-migration-v2 = ["schema-migration-api", "icydb-testing-test-sql-fixtures/migration-v2"]
test-admin-api = ["sql"]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
icydb = { path = "../../../crates/icydb", default-features = false, features = ["metrics"] }
icydb-model = { path = "../../../crates/icydb-model" }
icydb-testing-test-sql-fixtures = { workspace = true }

[build-dependencies]
icydb = { path = "../../../crates/icydb", default-features = false }
icydb-testing-test-sql-fixtures = { workspace = true }

[lints]
workspace = true
