[package]
name = "canister_test_startup_timer"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = []
candid-export = []

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-timers = { workspace = true }

[lints]
workspace = true
