[canisters.demo_rpg.sql]
readonly = true
ddl = true
fixtures = true

[canisters.demo_rpg.metrics]
enabled = true
reset = true

[canisters.demo_rpg.snapshot]
enabled = true

[canisters.demo_rpg.schema]
enabled = true
