[package]
name = "icydb-testing-audit-nested-relation-fixtures"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false
description = "Controlled nested-relation measurement schemas"

[package.metadata.cargo-machete]
ignored = ["candid", "icydb"]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
icydb = { path = "../../../crates/icydb", default-features = false }
icydb-model = { workspace = true }
icydb-testing-wasm-helpers = { workspace = true }

[lints]
workspace = true
