//! Runtime-only entity schema surface generated by macros.
//!
//! This model intentionally includes only:
//! - entity identity (path + stable external name)
//! - ordered fields
//! - primary key field
//! - index definitions
//!
//! It intentionally excludes:
//! - validators/sanitizers/defaults
//! - relations or full schema graphs
//! - JSON schema ingestion or global registries
//!
//! Stability: this is the authoritative runtime contract for planning and
//! execution. Additive changes are expected; breaking changes require a
//! coordinated version bump across the engine.
//!
//! Field names are entity-scoped. Callers that combine entities must
//! namespace by entity at the call site.

use crate::model::{field::EntityFieldModel, index::IndexModel};

/// Macro-generated runtime schema snapshot for a single entity.
///
/// The planner and predicate validator consume this model directly.
pub struct EntityModel {
    /// Fully-qualified Rust type path (for dispatch and diagnostics).
    pub path: &'static str,
    /// Stable external name used in keys and routing.
    pub entity_name: &'static str,
    /// Primary key field (points at an entry in `fields`).
    pub primary_key: &'static EntityFieldModel,
    /// Ordered field list (authoritative for runtime planning).
    pub fields: &'static [EntityFieldModel],
    /// Index definitions (field order is significant).
    pub indexes: &'static [&'static IndexModel],
}
