[package]
name = "icydb-testing-model-schema-only"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false
license = { workspace = true }
description = "Schema-only compile fixture for the standalone IcyDB model package"
repository = { workspace = true }
authors = { workspace = true }

[dependencies]
model_api = { package = "icydb-model", path = "../../crates/icydb-model" }
runtime_api = { package = "icydb", path = "../../crates/icydb", default-features = false }

[lints]
workspace = true
