[package]
name = "canister_audit_one_entity_typed_query"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false

[package.metadata.cargo-machete]
ignored = ["candid", "icydb-testing-audit-one-simple-fixtures"]

[lib]
crate-type = ["cdylib"]

[features]
default = []
candid-export = []
exact-key-measurement = []
lifecycle-audit = []
lifecycle-participant = []
u256-audit = [
    "icydb-testing-audit-one-simple-fixtures/u256-audit",
]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
icydb = { path = "../../../crates/icydb", default-features = false }
icydb-testing-audit-one-simple-fixtures = { workspace = true }

[build-dependencies]
icydb = { path = "../../../crates/icydb", default-features = false }
icydb-testing-audit-one-simple-fixtures = { workspace = true }

[lints]
workspace = true
