[package]
name = "canister_audit_sql_perf"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false

[package.metadata.cargo-machete]
ignored = ["serde"]

[lib]
crate-type = ["cdylib"]

[features]
default = []
candid-export = []
sql = ["icydb/sql"]
diagnostics = ["icydb/diagnostics"]
test-admin-api = ["sql"]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-timers = { workspace = true }
icydb = { path = "../../../crates/icydb", default-features = false }
icydb-testing-audit-sql-perf-fixtures = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
icydb = { path = "../../../crates/icydb", default-features = false }
icydb-testing-audit-sql-perf-fixtures = { workspace = true }

[lints]
workspace = true
