[package]
name = "icydb-testing-model-facade-only"
build = "src/build.rs"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false
license = { workspace = true }
description = "Compile contract for model authoring through the IcyDB facade"
repository = { workspace = true }
authors = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
runtime_api = { package = "icydb", path = "../../crates/icydb" }

[build-dependencies]
runtime_api = { package = "icydb", path = "../../crates/icydb" }

[dev-dependencies]
ic-memory = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
